### ISSUE TITLE
Can't run from `packages/` dir

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor-webpack-support#21]
See [this gist](https://gist.github.com/EmilianoJordan/170c5e2f9c4436248052983085412d6c) (cc @EmilianoJordan)

I can reproduce this. I haven't completely narrowed in on the cause, but if you comment out `extras_require` https://github.com/lektor/lektor-webpack-support/blob/master/setup.py#L28, then you can install it, and `lektor server` will succeed. That line and the related lines look fine to me though. I'm suspicious this is an upstream error in `pip` or `lektor`, but I'm not sure, so we can track it here for now. An update to Lektor's core may fix this or offer a workaround as well.

I'm running `pip 10.0.1` and master of this repo and Lektor.

**Comment by yagebu** [comment]
The extras_require has been removed. Since this now only has a setup.cfg and no more setup.py, this package still can't be used from the packages dir since Lektor won't recognize it as a package - the local package installation should be deprecated anyway in Lektor - if one wants a local install, it should be done explicitly in the local virtual env/pipenv/poetry. I'll hence close this as a wontfix (if at all this is now solely a Lektor-issue)
